name: UltraGpuImage
targets:
  UltraGpuImage:
    type: library.static
    platform: iOS
    deploymentTarget: "9.0"
    sources:
      - path: src
    settings:
      GCC_PREPROCESSOR_DEFINITIONS: "$(inherited) GLES_SILENCE_DEPRECATION=1"
      CONFIGURATION_BUILD_DIR: "$(PROJECT_DIR)/../libs/"
      CLANG_WARN_DOCUMENTATION_COMMENTS: "NO"
      ENABLE_BITCODE: "NO"
      ONLY_ACTIVE_ARCH: "NO"
      SKIP_INSTALL: "YES"
